export const wordBank = [
    'Breakfast Menu',
    'Rollerblade',
    'Cookie Crumbs',
    'Surprise Birthday Party',
    'Pie Crust',
    'Hey, batter, batter!',
    'Small Fry',
    'Salad Bar',
    'Animal Cracker',
    'Bad Apple',
    'Catnap',
    'Cotton Candy',
    'Ejection Seat',
    'Bagpipes',
    'Babysitter',
    'Hacky Sack',
    'Full Circle',
    'Close Encounter',
    'Anteater',
    'Caesar Salad',
    'Carrot Cake',
    'Bird Cage',
    'Poop Scoop',
    'Snow Angel',
    'Spider Bite',
    'Road Rage',
    'Water Balloon Fight',
    'Sand Castle',
    'Funny Bone',
    'Disposable Camera',
    'Barn Owl',
    'Massage Table',
    'Radioactive',
    'Sponge Bath',
    'Movie Popcorn',
    'Puppy Party',
    'Bounce Back',
    'Paintbrush',
    'Clam Chowder',
    'Pickle Jar',
    'Free Advice',
    'Alligator Wrestling',
    'Sandstorm',
    'Waffle Cone',
    'Pump Iron',
    'Parade Float',
    'Wedding Crasher',
    'Lightning Bug',
    'Pumpkin Patch',
    'Winter Break',
  ];